ebokyung/eggplant-market-react

- .eslintrc
- .jsconfig.json
- package-lock.json
- package.json
- src/App.js
- src/routes/index.js
<br>
- 프로젝트 세팅
- 라우터 추가
<br>
- eslint 설정과 package.json 확인해주세요
- jsconfig 확인해주세요
<br>
- 
<br><br>
> 프로젝트 세팅 추가 및 라우터 설정

- .eslintrc
- src/components/Element/Header/Header.scss
- src/components/Element/Post/Post.jsx
- src/components/Element/Post/Post.scss
- src/components/Element/Post/index.js
- src/components/Element/User/style/User.scss
- src/components/Element/index.js
- src/libs/dummy/posts.js
- src/pages/Home/components/HomeWithPost.jsx
- src/pages/Home/components/HomeWithoutPost.jsx
- src/pages/Home/components/index.js
- src/pages/Home/index.js
- src/pages/Home/routes/Home.jsx
- src/pages/Home/style/Home.scss
- src/routes/index.js
<br>
- 홈 화면 작업
- routes/Home : 홈화면 컴포넌트 모아서 처리하는 역할입니다
- 게시글 컴포넌트에서 있던 오류 수정했습니다
- Header에 font-weight 필요해서 추가했습니다
<br>
- 아직 검색 페이지랑 연결을 안했는데, 검색페이지 작업하면서 연결하겠습니당
- 추후에 User 컴포넌트 날잡고 공사 해야할수도 있음,,
- 링크, 프롭 관련
- 이미지 관련해서는 아직 util을 안뽑아와서 빈 이미지가 뜰 수 있어요
- 이 함수도 수정 필요~
<br>
- #17 
<br><br>
> 홈화면 마크업, 디자인

- src/components/Element/Post/ButtonLike.jsx
- src/components/Element/Post/Post.jsx
<br>
- [좋아요 버튼에 id 프롭 추가]
- [이미지 여러개 처리]
<br>
- 없습니다
<br>
- #33
<br><br>
> 게시글 컴포넌트 수정

- src/configs/config.js
- src/libs/axios.js
- src/utils/storage.js
<br>
- axios 관련된 기본적인거 넣어놨어용
-
<br>
- 테스트는 전부 해보진 않앗는데,, 이슈 있으면 그때 필요한거 추가하거나 수정하면 될거 같슴다
- 사용방법 모르시겠으면 따로 알려드릴게여
<br>
- #52 
<br><br>
> add : axios 관련 세팅 추가 (#52)

- src/pages/Profile/routes/UserProfile.jsx
- [] 기능 추가 :
<br>
-
<br>
-
<br>
- #25
<br><br>
> fix : 프로필 페이지에서 프로필 페이지로 이동시 버그 수정

- src/components/Element/Input/InputImg.jsx
- src/components/Element/User/ProfileImg.jsx
- src/components/Element/User/User.jsx
- src/components/Information/Information.jsx
- src/components/InputComponents/InputAcctname.jsx
- src/components/InputComponents/InputEmail.jsx
- src/components/InputComponents/InputIntro.jsx
- src/libs/api/PostImage.js
- src/pages/EditProfile/api/index.js
- src/pages/EditProfile/routes/EditProfile.jsx
- src/pages/Product/api/index.js
- src/pages/Product/components/InputProductImage.jsx
- src/pages/Product/components/ProductForm.jsx
- src/pages/Profile/components/ProfileSectionElement/ButtonsMyProfile.jsx
- src/pages/SignUp/api/index.js
- src/pages/SignUp/routes/SignUp.jsx
<br>
- 회원가입 및 프로필 설정 pages/signup
- 프로필 수정 pages/editprofile
- 자잘 수정
<br>
- 이미지 서버에 올리고 filename 받아오는 API 요청 함수 
공통으로 사용할 수 있도록 폴더 경로 변경했습니다 (libs/api/PostImage.js)
<br>
- #46 
<br><br>
> add : 회원가입 및 프로필 수정 페이지 API 연결

- src/components/Element/Input/InputImg.jsx
- src/pages/Post/api/index.js
- src/pages/Post/components/Comment.jsx
- src/pages/Post/components/CommentInput.jsx
- src/pages/Post/routes/PostDetail.jsx
- src/pages/Post/style/CommentInput.scss
- src/pages/Posting/components/ImageItem.jsx
- src/pages/Product/components/InputProductImage.jsx
- src/pages/Search/routes/Search.jsx
<br>
- get 요청 후 뿌리기
- 댓글 기능
- 댓글 제출하면 데이터 갱신
<br>
- 작동 gif
- 댓글 제출 한번만 되게 했서요
- 엔터도 되게 하려고 form으로 묶었슴니다
<br>
- #37 
<br><br>
> Feat : post page

- src/components/Element/Post/Post.jsx
- src/libs/constant/regex.js
- src/pages/Posting/api/index.js
- src/pages/Posting/components/ImageArea.jsx
- src/pages/Posting/components/ImageItem.jsx
- src/pages/Posting/routes/Posting.jsx
- src/pages/Profile/components/PostSectionElement/AlbumView.jsx
<br>
- ,랑 공백 정규표현식 처리
- 게시글 등록
- 게시글 수정
<br>
- 게시글 수정할때 postId 있으면 게시글 다 받아오고 없으면 유저 정보만 가져옵니당
- 갑자기 든 생각은 로그인한 유저 프로필 사진같은거,, 짜잘짜잘하게 은근 쓰이는데 전역적으로 쓸수 있는 방법 있으면 조을거 같아요
- ex) recoil async selector
- 그 외로도 짜잘짜잘하게 여러군데서 쓰이는거 모아놓고 얘기하면 조을거 같아요
- 둘다 테스트는 완료
- 업로드는 여러번 눌러도 한번만 반영
<br>
- #48 
<br><br>
> Feat : posting

- src/libs/dummy/chatRoom.js
- src/pages/ChatList/components/ChatListItem.jsx
- src/pages/ChatRoom/routes/ChatRoom.jsx
<br>
- 채팅방 더미 데이터 수정
- 채팅목록에서 누르는 채팅방 id에 맞는 더미데이터 뿌리게 연결했습니다
<br>
- 채팅목록-채팅방 연결 안되던거 더미데이터 수정해서 연결했어요
<br>
- #19 
<br><br>
> refactor : 채팅목록-채팅방 더미 데이터 수정 및 roomId에 맞는 데이터 렌더링

- src/pages/EditProfile/routes/EditProfile.jsx
<br>
-
<br>
-
<br>
- #46 
<br><br>
> design : 프로필 수정 페이지 스켈레톤

- src/components/Element/Post/Post.scss
- src/components/Element/Post/PostSkeleton.jsx
- src/components/Skeleton/PostSkeleton.jsx
- src/index.js
- src/pages/Home/routes/Home.jsx
- src/pages/Post/components/CommentInputSkeleton.jsx
- src/pages/Post/components/CommentSkeleton.jsx
- src/pages/Post/routes/PostDetail.jsx
- src/pages/Post/style/Comment.scss
- src/styles/scss/global.scss
<br>
-
-
<br>
-
<br>
- 
<br><br>
> design : 게시글 관련 스켈레톤 작업 (PR 작성중)

- src/pages/Product/components/InputProductImage.jsx
- src/pages/Profile/routes/UserProfile.jsx
- src/pages/Profile/styles/ProductSection.scss
<br>
<br>
- 게시글 스켈레톤 만들어지면 추후 적용하겠습니다
<br>
- #25 
<br><br>
> design : 사용자프로필 페이지 스켈레톤

- src/pages/Follow/routes/Follow.jsx
<br>
-
-
<br>
-
<br>
- 
<br><br>
> refactor : setTimeout 삭제

- src/pages/Post/components/CommentInputSkeleton.jsx
- src/pages/Post/routes/PostDetail.jsx
<br>
- 댓글 입력시 무한 로딩 되는 현상이 있었는데 수정했습니다
-
<br>
-
<br>
- 
<br><br>
> fix : 댓글 입력 버그 수정

- src/components/Element/Input/InputImg.jsx
- src/components/Element/Post/Post.jsx
- src/components/Element/Post/Post.scss
- src/hooks/scroll.js
- src/libs/api/fetchClosure.js
- src/pages/ChatRoom/routes/ChatRoom.jsx
- src/pages/Follow/routes/Follow.jsx
- src/pages/Home/api/index.js
- src/pages/Home/routes/Home.jsx
- src/pages/Posting/components/ImageArea.jsx
- src/pages/Product/components/InputProductImage.jsx
- src/pages/Profile/routes/UserProfile.jsx
- src/utils/scroll.js
<br>
-
-
<br>
- 훅 만들면서 코드가 일부 수정됐어용
<br>
- 
<br><br>
> Feat : 무한 스크롤

- src/components/Element/Post/Post.jsx
- src/hooks/useLazyLoad.jsx
- src/pages/Profile/components/ProductSectionElement/ProductItem.jsx
<br>
- 게시글 이미지 지연 로딩
- 판매 상품 이미지 지연 로딩
<br>
- strict mode에서 에러나요
<br>
- #82
<br><br>
> add : 이미지 지연 로딩

- package-lock.json
- package.json
- src/components/Element/Header/Header.jsx
- src/components/Element/Header/Header.scss
- src/components/Element/Post/Post.jsx
- src/components/Element/Post/Post.scss
- src/libs/dummy/index.js
<br>
<br>
- 없습니다
<br>
- #82 
<br><br>
> refactor : 아이콘 사이즈 고정

- src/hooks/useLazyLoad.jsx
<br>
-
-
<br>
-
<br>
- 
<br><br>
> fix: useLazyLoad options 제거

- src/pages/Post/style/CommentInput.scss
<br>
- 없습니당
<br>
- 없습니당
<br>
- 
<br><br>
> fix : '게시' 사이즈 수정

- src/components/Element/Header/Header.jsx
- src/components/Element/Navbar/Navbar.jsx
- src/components/Element/SkipNav/SkipNav.jsx
- src/components/Element/SkipNav/SkipNav.scss
- src/pages/Home/components/HomeWithPost.jsx
- src/pages/Home/components/HomeWithoutPost.jsx
- src/pages/Home/routes/Home.jsx
- src/pages/Post/components/CommentInput.jsx
- src/pages/Post/routes/PostDetail.jsx
- src/pages/Profile/components/PostSection.jsx
- src/pages/Profile/routes/UserProfile.jsx
- src/utils/imageUrlProcess.js
<br>
- recoil로 theme 상태를 관리할 시에, 새로고침을 하면 해당 상태가 초기화되어 수정페이지 진입 시에 checImageUrl 에서 아톰을 부를때 버그가 생기는것 같습니다
일단 localStroage로 해결했는데, recoil을 사용할 것이라면 아마 recoil-persist로 해결해야할것 같습니당
- 
-
<br>
-
<br>
- 
<br><br>
> add : skipnavigation 부착 + 수정페이지 진입 버그 해결

- src/pages/SignUp/routes/SignUp.jsx
<br>
- 감귤 -> 가지
<br>
-
<br>
- 
<br><br>
> fix : 회원가입 버튼 문구 변경

- public/index.html
- public/reset.css
- src/index.js
- src/libs/Meta.jsx
<br>
- js로 scss들을 동적으로 불러오는 방식보다, index.html에서 부르는 방식이 성능면에서 우수한것으로 보여서 수정했습니다
-
<br>
- 카카오톡으로 보내드린 노션 기록 봐주세욥
<br>
- 
<br><br>
> 초기 css 로드 방식 변경

- public/index.html
- src/components/Element/User/ProfileImg.jsx
- src/index.js
- src/pages/Home/routes/Home.jsx
<br>
- 없습니다
-
<br>
- 없습니다
<br>
- 
<br><br>
> fix : theme 기능 누락 수정
